steps:
  - name: ":node:"
    command: "npm install && npm test"

  - name: ":node2:"
    command: "npm install && npm pack --unsafe-perm"

  - name: ":node3:"
    command: "pip install --upgrade cloudsmith-cli"
  