steps:
  - name: ":node:"
    command: "npm install && npm test"
  -name: "build package"
    command: "npm pack"
  -name: "publish to cloudsmith"
    command: "pip install --upgrade cloudsmith-cli"
  